# Generated by Django 4.2.6 on 2023-10-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_routes_instructor_location_covered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='locations',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='routes',
            old_name='location_covered',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='location_covered',
        ),
    ]
