# Generated by Django 4.2.6 on 2023-10-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_instructor_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='qualification',
        ),
        migrations.AddField(
            model_name='instructor',
            name='confirm_password',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='instructor',
            name='location',
            field=models.CharField(choices=[('Ekoro', 'Bachelor of Science'), ('Meiran Road', 'Master'), ('Agege', 'Bachelor of Arts'), ('Fagba', 'National Certificate Examination')], default='0', max_length=20),
        ),
    ]
