# Generated by Django 4.2.6 on 2023-10-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_instructor_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='confirm_password',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='location',
            field=models.CharField(choices=[('Ekoro', 'Ekoro'), ('Meiran Road', 'Meiran Road'), ('Agege', 'Agege'), ('Fagba', 'Fagba')], default='null', max_length=20),
        ),
    ]
